/* 
 * FAILING TEST FILE: PPX_ExternalGeneration__test.re
 * 
 * PURPOSE: This test verifies that external declarations are properly generated by the PPX
 *          when data attributes are used with JSX elements.
 * 
 * EXPECTED FAILURE: Tests fail with "Unbound value makeProps_*" compilation errors
 * because the external declarations are NOT being generated by the PPX.
 * 
 * This proves the PPX deduplication bug prevents external declarations from being output.
 */

open Jest;
open Expect;

describe("PPX External Declaration Generation", () => {
  describe("External declarations for data attributes", () => {
    
    // CRITICAL: This test MUST fail initially with "Unbound value makeProps_*" errors
    // because the PPX is not generating the required external declarations
    test("should fail compilation due to missing external makeProps_div_* declarations", () => {
      // These JSX elements require external declarations to be generated by the PPX
      // EXPECTED FAILURE: Compilation error "Unbound value makeProps_div_[hash]"
      let _testElement1 = <div data_testid="test" />;
      
      // This should compile if external declarations are properly generated
      expect(Js.typeof(_testElement1))->toBe("object");
    });
    
    test("should fail compilation for kebab-case data attributes", () => {
      // Element with underscore data attribute (should transform to kebab-case)
      // EXPECTED FAILURE: Compilation error "Unbound value makeProps_div_[hash]"
      let _testElement = <div data_test_id="underscore" />;
      
      expect(Js.typeof(_testElement))->toBe("object");
    });
    
    test("should fail compilation for different element types with data attributes", () => {
      // Different element types should generate different external functions
      // EXPECTED FAILURE: Multiple "Unbound value makeProps_*" errors
      let _divElement = <div data_testid="div-test" />;
      let _spanElement = <span data_role="span-test" />;
      let _buttonElement = <button data_analytics="button-test" />;
      
      expect(Js.typeof(_divElement))->toBe("object");
      expect(Js.typeof(_spanElement))->toBe("object");
      expect(Js.typeof(_buttonElement))->toBe("object");
    });
    
    test("should fail compilation with deduplication issue for same data attributes", () => {
      // Multiple elements with same data attributes should reuse same external
      // EXPECTED FAILURE: Compilation error for all elements
      let _element1 = <div data_testid="test1" />;
      let _element2 = <div data_testid="test2" />; // Same structure, different value
      let _element3 = <div data_testid="test3" />; // Should reuse same external
      
      expect(Js.typeof(_element1))->toBe("object");
      expect(Js.typeof(_element2))->toBe("object");
      expect(Js.typeof(_element3))->toBe("object");
    });
    
    test("should fail compilation for elements with multiple data attributes", () => {
      // Element with multiple data attributes needs complex external signature
      // EXPECTED FAILURE: Compilation error "Unbound value makeProps_div_[hash]"
      let _element = <div data_testid="test" data_role="button" data_value="example" />;
      
      expect(Js.typeof(_element))->toBe("object");
    });
    
    test("should fail compilation for components with data attributes in modules", () => {
      // Component that uses data attributes in nested module context
      module TestComponent = {
        [@react.component]
        let make = (~testProp) => {
          // EXPECTED FAILURE: Compilation error "Unbound value makeProps_div_[hash]"
          <div data_component="test" data_prop={testProp}>
            {React.string("Test component")}
          </div>;
        };
      };
      
      let _component = <TestComponent testProp="value" />;
      
      expect(Js.typeof(_component))->toBe("object");
    });
  });
  
  describe("PPX external generation integration", () => {
    test("should fail compilation when externals are missing (core issue)", () => {
      // This test demonstrates the core issue: PPX references externals that don't exist
      // EXPECTED FAILURE: Multiple "Unbound value makeProps_*" errors
      
      let _element1 = <div data_testid="callable-test-1" />;
      let _element2 = <span data_role="callable-test-2" />;
      let _element3 = <button data_analytics="callable-test-3" />;
      
      // These will fail to compile because external declarations are missing
      expect(Js.typeof(_element1))->toBe("object");
      expect(Js.typeof(_element2))->toBe("object");
      expect(Js.typeof(_element3))->toBe("object");
    });
    
    testAsync("should fail compilation for async components with data attributes", finish => {
      // Async test component that uses data attributes
      module RenderTest = {
        [@react.component]
        let make = () => {
          React.useEffect0(() => {
            finish();
            None;
          });
          
          // EXPECTED FAILURE: Compilation error "Unbound value makeProps_div_[hash]"
          <div data_testid="render-integration" data_framework="reason-react">
            {React.string("Integration test")}
          </div>;
        };
      };
      
      // This will fail to compile if externals are not properly generated
      let _component = <RenderTest />;
      ();
    });
  });
});