lib: [
  "_build/install/default/lib/reactjs_jsx_ppx_v3/META" {"META"}
  "_build/install/default/lib/reactjs_jsx_ppx_v3/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/reactjs_jsx_ppx_v3" {"reactjs_jsx_ppx_v3"}
]
doc: [
  "_build/install/default/doc/reactjs_jsx_ppx_v3/HISTORY.md"
  "_build/install/default/doc/reactjs_jsx_ppx_v3/LICENSE"
  "_build/install/default/doc/reactjs_jsx_ppx_v3/README.md"
]
