
  $ cat >dune-project <<EOF
  > (lang dune 3.9)
  > (using melange 0.1)
  > EOF

  $ cat >dune <<EOF
  > (melange.emit
  >  (target js-out)
  >  (emit_stdlib false)
  >  (libraries reason-react))
  > EOF

  $ cat >x.ml <<EOF
  > let cb = React.useCallback0(fun a b -> a + b)
  > EOF

  $ dune build @melange
  $ cat _build/default/js-out/x.js
  // Generated by Melange
  'use strict';
  
  var React = require("react");
  
  var cb = React.useCallback((function (a) {
          return function (b) {
            return a + b | 0;
          };
        }), []);
  
  exports.cb = cb;
  /* cb Not a pure module */
