
  $ cat >dune-project <<EOF
  > (lang dune 3.9)
  > (using melange 0.1)
  > EOF

  $ cat >dune <<EOF
  > (melange.emit
  >  (target js-out)
  >  (emit_stdlib false)
  >  (preprocess (pps melange.ppx))
  >  (libraries reason-react))
  > EOF

  $ cat >x.ml <<EOF
  > let cb = React.useCallback0(fun a b -> a + b)
  > EOF

  $ dune build @melange
  $ cat _build/default/js-out/x.js
  // Generated by Melange
  'use strict';
  
  const React = require("react");
  
  const cb = React.useCallback((function (a, b) {
    return a + b | 0;
  }), []);
  
  module.exports = {
    cb,
  }
  /* cb Not a pure module */

Using an Uncurried function:

  $ cat >x.ml <<EOF
  > let cb = React.useCallback0(fun[@u] a b -> a + b)
  > EOF

  $ dune clean
  $ dune build @melange
  $ cat _build/default/js-out/x.js
  // Generated by Melange
  'use strict';
  
  const React = require("react");
  
  const cb = React.useCallback((function (a, b) {
    return a + b | 0;
  }), []);
  
  module.exports = {
    cb,
  }
  /* cb Not a pure module */

